services:
  - type: web
    name: fallou-senghor-bank
    env: docker
    plan: free
    autoDeploy: true
    disks:
      - name: data
        mountPath: /var/www/html/storage
        sizeGB: 1

    envVars:
      - key: APP_NAME
        value: "Bank App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: "https://laravel-bank-app.onrender.com"
      - key: L5_SWAGGER_USE_HTTPS
        value: "true"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-steep-feather-adccnsal-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: FILESYSTEM_DISK
        value: local
    healthCheckPath: /api/health

