services:
  - type: web
    name: fallou-senghor-bank
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan key:generate
      php artisan l5-swagger:generate
    startCommand: |
      php-fpm -F -R &
      nginx -g "daemon off;" -c /etc/nginx/nginx.conf
    envVars:
      - key: APP_NAME
        value: "Bank App"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: "https://fallou-senghor-bank.onrender.com"
      - key: L5_SWAGGER_USE_HTTPS
        value: "true"
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-steep-feather-adccnsal-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_JTkO6wecp8Sr
      - key: DB_SSLMODE
        value: require
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: FILESYSTEM_DISK
        value: local
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/www/html/storage
      sizeGB: 1
